config/routes.rb
Rails.application.routes.draw do
  get "posts/index"
  get "posts/new"
  get "posts/create"
  get "posts/show"
  get "discussion_threads/index"
  get "discussion_threads/new"
  get "discussion_threads/create"
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "users/new"
  get "users/create"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker


  resources :users, only: [:new, :create]
  resources :posts, only: [:new, :create, :index, :show] do
    resources :replies, only: [:create]
  end
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  root 'users#new'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :replies, dependent: :destroy
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :posts
  has_many :replies

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true, format: {with: URI::MailTo::EMAIL_REGEXP}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user = User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user_logged_in!
    redirect_to login_path if current_user.nil?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user_logged_in!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :description)
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_action :require_user_logged_in!

  def create
    @post = Post.find(params[:post_id])
    @reply = @post.replies.build(reply_params)
    @reply.user = current_user

    if @reply.save
      redirect_to @post, notice: 'Reply was successfully posted.'
    else
      # If you want to show errors, you'd render the post show page again.
      # For simplicity, we'll just redirect with an alert.
      redirect_to @post, alert: 'Reply could not be posted.'
    end
  end

  private

  def reply_params
    params.require(:reply).permit(:content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to posts_path
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to posts_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Discussion Thread" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <h1 style="display:flex; align-items:center; justify-content:center;"> Discussion Threads</h1>
    <% if logged_in? %>
      <div style="position: absolute; top: 1rem; right: 1rem;">
        <%= button_to "Logout", logout_path, method: :delete %>
      </div>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/index.html.erb
<h1>All Posts</h1>

<% @posts.each do |post| %>
  <div>
    <h2><%= link_to post.title, post %></h2>
    <p>By: <%= post.user.email %></p>
  </div>
<% end %>

<%= link_to "New Post", new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_with model: @post do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.submit "Create Post" %>
  </div>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p>By: <%= @post.user.email %></p>

<p><%= @post.description %></p>

<hr>

<h3>Replies</h3>

<% @post.replies.each do |reply| %>
  <div>
    <p><strong><%= reply.user.name %></strong> (<%= reply.user.email %>) says:</p>
    <p><%= reply.content %></p>
    <small><%= time_ago_in_words(reply.created_at) %> ago</small>
  </div>

<% end %>

<% if logged_in? %>
  <h4>Add a reply:</h4>
  <%= form_with(model: [@post, @post.replies.build], local: true) do |form| %>
    <div>
      <%= form.label :content, "Your Reply" %><br>
      <%= form.text_area :content, rows: 4 %>
    </div>
    <div>
      <%= form.submit "Post Reply" %>
    </div>
  <% end %>
<% else %>
  <p><%= link_to "Log in", login_path %> to post a reply.</p>
<% end %>


<%= link_to "Back to all posts", posts_path %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<%= form_with model: @user do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div>
    <%= f.submit "Sign Up" %>
  </div>
<% end %>

<br>
<p>
  Already have an account? <%= link_to "Login", login_path %>
</p>